(function(d){var h=[];d.loadImages=function(a,e){"string"==typeof a&&(a=[a]);for(var f=a.length,g=0,b=0;b<f;b++){var c=document.createElement("img");c.onload=function(){g++;g==f&&d.isFunction(e)&&e()};c.src=a[b];h.push(c)}}})(window.jQuery);
var wl;

var lwi=-1;function thresholdPassed(){var w=$(window).width();var p=false;var cw=0;if(w>=480){cw++;}if(w>=768){cw++;}if(w>=960){cw++;}if(w>=1200){cw++;}if(w>=1920){cw++;}if(lwi!=cw){p=true;}lwi=cw;return p;}
ldsrcset=function(t){var e,r=document.querySelectorAll(t);for(e=0;e<r.length;e++){var c=r[e].getAttribute("data-srcset");r[e].setAttribute("srcset",c)}},ldsrc=function(t){var e=document.querySelector(t);if(e){var r=e.getAttribute("data-src");e.setAttribute("src",r)}};ldv=function(t){var e=document.querySelector(t);if(e){var r=document.querySelector(t+" source"),c=r.getAttribute("data-src");r.setAttribute("src",c),e.load()}};!function(){if("Promise"in window&&void 0!==window.performance){var e,t,r=document,n=function(){return r.createElement("link")},o=new Set,a=n(),i=a.relList&&a.relList.supports&&a.relList.supports("prefetch"),s=location.href.replace(/#[^#]+$/,"");o.add(s);var c=function(e){var t=location,r="http:",n="https:";if(e&&e.href&&e.origin==t.origin&&[r,n].includes(e.protocol)&&(e.protocol!=r||t.protocol!=n)){var o=e.pathname;if(!(e.hash&&o+e.search==t.pathname+t.search||"?preload=no"==e.search.substr(-11)||".html"!=o.substr(-5)&&".html"!=o.substr(-5)&&"/"!=o.substr(-1)))return!0}},u=function(e){var t=e.replace(/#[^#]+$/,"");if(!o.has(t)){if(i){var a=n();a.rel="prefetch",a.href=t,r.head.appendChild(a)}else{var s=new XMLHttpRequest;s.open("GET",t,s.withCredentials=!0),s.send()}o.add(t)}},p=function(e){return e.target.closest("a")},f=function(t){var r=t.relatedTarget;r&&p(t)==r.closest("a")||e&&(clearTimeout(e),e=void 0)},d={capture:!0,passive:!0};r.addEventListener("touchstart",function(e){t=performance.now();var r=p(e);c(r)&&u(r.href)},d),r.addEventListener("mouseover",function(r){if(!(performance.now()-t<1200)){var n=p(r);c(n)&&(n.addEventListener("mouseout",f,{passive:!0}),e=setTimeout(function(){u(n.href),e=void 0},80))}},d)}}();

$(function(){
r=function(){if(thresholdPassed()){dpi=window.devicePixelRatio;if($(window).width()>=1920){var e=document.querySelector('.un5');e.setAttribute('src','images/mask-group-693.png');
var e=document.querySelector('.un6');e.setAttribute('src','images/exclude-170-1.png');
var e=document.querySelector('.un8');e.setAttribute('src','images/ideate_icon-316-1.png');
var e=document.querySelector('.un9');e.setAttribute('src','images/design_icon-316-1.png');
var e=document.querySelector('.un10');e.setAttribute('src','images/webd_icon-316-1.png');
var e=document.querySelector('.un11');e.setAttribute('src','images/appd_icon-316-1.png');
var e=document.querySelector('.un12');e.setAttribute('src','images/businessg_icon-316-1.png');
var e=document.querySelector('.un13');e.setAttribute('src','images/digitalm_icon-316-1.png');
var a='data-src';var e=document.querySelector('.un15');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/philips-315.png');
var a='data-src';var e=document.querySelector('.un16');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/fedex-209-1.png');
var a='data-src';var e=document.querySelector('.un17');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/jeep-165.png');
var a='data-src';var e=document.querySelector('.un18');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/pirelli-267.png');
var a='data-src';var e=document.querySelector('.un19');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/obitcoin-275.png');
var a='data-src';var e=document.querySelector('.un20');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/jquery-257-1.png');
var a='data-src';var e=document.querySelector('.un21');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/amazon-194-1.png');
var a='data-src';var e=document.querySelector('.un22');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/hubspot-202-1.png');
var a='data-src';var e=document.querySelector('.un23');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/careem-246-1.png');
var a='data-src';var e=document.querySelector('.un24');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/canon-225-1.png');
var a='data-src';var e=document.querySelector('.un25');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/officemap-728.png');}else if($(window).width()>=1200){var e=document.querySelector('.un5');e.setAttribute('src','images/mask-group-498.png');
var e=document.querySelector('.un6');e.setAttribute('src','images/exclude-106.png');
var e=document.querySelector('.un8');e.setAttribute('src','images/ideate_icon-197.png');
var e=document.querySelector('.un9');e.setAttribute('src','images/design_icon-197.png');
var e=document.querySelector('.un10');e.setAttribute('src','images/webd_icon-197.png');
var e=document.querySelector('.un11');e.setAttribute('src','images/appd_icon-197.png');
var e=document.querySelector('.un12');e.setAttribute('src','images/businessg_icon-197.png');
var e=document.querySelector('.un13');e.setAttribute('src','images/digitalm_icon-197.png');
var a='data-src';var e=document.querySelector('.un15');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/philips-195.png');
var a='data-src';var e=document.querySelector('.un16');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/fedex-130.png');
var a='data-src';var e=document.querySelector('.un17');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/jeep-103.png');
var a='data-src';var e=document.querySelector('.un18');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/pirelli-166.png');
var a='data-src';var e=document.querySelector('.un19');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/obitcoin-171.png');
var a='data-src';var e=document.querySelector('.un20');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/jquery-159.png');
var a='data-src';var e=document.querySelector('.un21');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/amazon-120.png');
var a='data-src';var e=document.querySelector('.un22');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/hubspot-125.png');
var a='data-src';var e=document.querySelector('.un23');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/careem-154.png');
var a='data-src';var e=document.querySelector('.un24');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/canon-141.png');
var a='data-src';var e=document.querySelector('.un25');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/officemap-455.png');}else if($(window).width()>=960){var e=document.querySelector('.un5');e.setAttribute('src',(dpi>1)?'images/mask-group-790.png':'images/mask-group-395.png');
var e=document.querySelector('.un6');e.setAttribute('src',(dpi>1)?'images/exclude-170.png':'images/exclude-85.png');
var e=document.querySelector('.un8');e.setAttribute('src','images/ideate_icon-158.png');
var e=document.querySelector('.un9');e.setAttribute('src','images/design_icon-158.png');
var e=document.querySelector('.un10');e.setAttribute('src','images/webd_icon-158.png');
var e=document.querySelector('.un11');e.setAttribute('src','images/appd_icon-158.png');
var e=document.querySelector('.un12');e.setAttribute('src','images/businessg_icon-158.png');
var e=document.querySelector('.un13');e.setAttribute('src','images/digitalm_icon-158.png');
var a='data-src';var e=document.querySelector('.un15');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/philips-157.png');
var a='data-src';var e=document.querySelector('.un16');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/fedex-104.png');
var a='data-src';var e=document.querySelector('.un17');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/jeep-82.png');
var a='data-src';var e=document.querySelector('.un18');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/pirelli-133.png');
var a='data-src';var e=document.querySelector('.un19');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/obitcoin-138.png');
var a='data-src';var e=document.querySelector('.un20');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/jquery-128.png');
var a='data-src';var e=document.querySelector('.un21');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/amazon-97.png');
var a='data-src';var e=document.querySelector('.un22');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/hubspot-101.png');
var a='data-src';var e=document.querySelector('.un23');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/careem-246.png':'images/careem-123.png');
var a='data-src';var e=document.querySelector('.un24');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/canon-226.png':'images/canon-113.png');
var a='data-src';var e=document.querySelector('.un25');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/officemap-364.png');}else if($(window).width()>=768){var e=document.querySelector('.un5');e.setAttribute('src',(dpi>1)?'images/mask-group-734.png':'images/mask-group-367.png');
var e=document.querySelector('.un6');e.setAttribute('src',(dpi>1)?'images/exclude-136.png':'images/exclude-68.png');
var e=document.querySelector('.un8');e.setAttribute('src','images/ideate_icon-126.png');
var e=document.querySelector('.un9');e.setAttribute('src','images/design_icon-126.png');
var e=document.querySelector('.un10');e.setAttribute('src','images/webd_icon-126.png');
var e=document.querySelector('.un11');e.setAttribute('src','images/appd_icon-126.png');
var e=document.querySelector('.un12');e.setAttribute('src','images/businessg_icon-126.png');
var e=document.querySelector('.un13');e.setAttribute('src','images/digitalm_icon-126.png');
var a='data-src';var e=document.querySelector('.un15');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/philips-250.png':'images/philips-125.png');
var a='data-src';var e=document.querySelector('.un16');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/fedex-166.png':'images/fedex-83.png');
var a='data-src';var e=document.querySelector('.un17');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/jeep-132.png':'images/jeep-66.png');
var a='data-src';var e=document.querySelector('.un18');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/pirelli-212.png':'images/pirelli-106.png');
var a='data-src';var e=document.querySelector('.un19');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/obitcoin-218.png':'images/obitcoin-109.png');
var a='data-src';var e=document.querySelector('.un20');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/jquery-204.png':'images/jquery-102.png');
var a='data-src';var e=document.querySelector('.un21');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/amazon-154.png':'images/amazon-77.png');
var a='data-src';var e=document.querySelector('.un22');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/hubspot-160.png':'images/hubspot-80.png');
var a='data-src';var e=document.querySelector('.un23');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/careem-196.png':'images/careem-98.png');
var a='data-src';var e=document.querySelector('.un24');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/canon-178.png':'images/canon-89.png');
var a='data-src';var e=document.querySelector('.un25');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/officemap-582.png':'images/officemap-291.png');}else if($(window).width()>=480){var e=document.querySelector('.un5');e.setAttribute('src',(dpi>1)?'images/mask-group-458.png':'images/mask-group-229.png');
var e=document.querySelector('.un6');e.setAttribute('src',(dpi>1)?'images/exclude-84.png':'images/exclude-42.png');
var e=document.querySelector('.un8');e.setAttribute('src',(dpi>1)?'images/ideate_icon-160.png':'images/ideate_icon-80.png');
var e=document.querySelector('.un9');e.setAttribute('src',(dpi>1)?'images/design_icon-160.png':'images/design_icon-80.png');
var e=document.querySelector('.un10');e.setAttribute('src',(dpi>1)?'images/webd_icon-160.png':'images/webd_icon-80.png');
var e=document.querySelector('.un11');e.setAttribute('src',(dpi>1)?'images/appd_icon-160.png':'images/appd_icon-80.png');
var e=document.querySelector('.un12');e.setAttribute('src',(dpi>1)?'images/businessg_icon-160.png':'images/businessg_icon-80.png');
var e=document.querySelector('.un13');e.setAttribute('src',(dpi>1)?'images/digitalm_icon-160.png':'images/digitalm_icon-80.png');
var a='data-src';var e=document.querySelector('.un15');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/philips-160.png':'images/philips-80.png');
var a='data-src';var e=document.querySelector('.un16');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/fedex-106.png':'images/fedex-53.png');
var a='data-src';var e=document.querySelector('.un17');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/jeep-84.png':'images/jeep-42.png');
var a='data-src';var e=document.querySelector('.un18');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/pirelli-136.png':'images/pirelli-68.png');
var a='data-src';var e=document.querySelector('.un19');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/obitcoin-138-1.png':'images/obitcoin-69.png');
var a='data-src';var e=document.querySelector('.un20');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/jquery-130.png':'images/jquery-65.png');
var a='data-src';var e=document.querySelector('.un21');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/amazon-100.png':'images/amazon-50.png');
var a='data-src';var e=document.querySelector('.un22');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/hubspot-102.png':'images/hubspot-51.png');
var a='data-src';var e=document.querySelector('.un23');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/careem-124.png':'images/careem-62.png');
var a='data-src';var e=document.querySelector('.un24');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/canon-112.png':'images/canon-56.png');
var a='data-src';var e=document.querySelector('.un25');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/officemap-364-1.png':'images/officemap-182.png');}else{var e=document.querySelector('.un5');e.setAttribute('src',(dpi>1)?'images/mask-group-306.png':'images/mask-group-153.png');
var e=document.querySelector('.un6');e.setAttribute('src',(dpi>1)?'images/exclude-56.png':'images/exclude-28.png');
var e=document.querySelector('.un8');e.setAttribute('src',(dpi>1)?'images/ideate_icon-106.png':'images/ideate_icon-53.png');
var e=document.querySelector('.un9');e.setAttribute('src',(dpi>1)?'images/design_icon-106.png':'images/design_icon-53.png');
var e=document.querySelector('.un10');e.setAttribute('src',(dpi>1)?'images/webd_icon-106.png':'images/webd_icon-53.png');
var e=document.querySelector('.un11');e.setAttribute('src',(dpi>1)?'images/appd_icon-106.png':'images/appd_icon-53.png');
var e=document.querySelector('.un12');e.setAttribute('src',(dpi>1)?'images/businessg_icon-106.png':'images/businessg_icon-53.png');
var e=document.querySelector('.un13');e.setAttribute('src',(dpi>1)?'images/digitalm_icon-106.png':'images/digitalm_icon-53.png');
var a='data-src';var e=document.querySelector('.un15');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/philips-106.png':'images/philips-53.png');
var a='data-src';var e=document.querySelector('.un16');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/fedex-70.png':'images/fedex-35.png');
var a='data-src';var e=document.querySelector('.un17');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/jeep-56.png':'images/jeep-28.png');
var a='data-src';var e=document.querySelector('.un18');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/pirelli-90.png':'images/pirelli-45.png');
var a='data-src';var e=document.querySelector('.un19');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/obitcoin-92.png':'images/obitcoin-46.png');
var a='data-src';var e=document.querySelector('.un20');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/jquery-86.png':'images/jquery-43.png');
var a='data-src';var e=document.querySelector('.un21');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/amazon-66.png':'images/amazon-33.png');
var a='data-src';var e=document.querySelector('.un22');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/hubspot-68.png':'images/hubspot-34.png');
var a='data-src';var e=document.querySelector('.un23');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/careem-82.png':'images/careem-41.png');
var a='data-src';var e=document.querySelector('.un24');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/canon-76.png':'images/canon-38.png');
var a='data-src';var e=document.querySelector('.un25');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/officemap-242.png':'images/officemap-121.png');}}};
if(!window.HTMLPictureElement){$(window).resize(r);r();}
!function(){var e=document.querySelectorAll('a[href^="#"]');[].forEach.call(e,function(e){e.addEventListener("click",function(t){var o=0;if(e.hash.length>1){var n=parseFloat(getComputedStyle(document.body).getPropertyValue("zoom"));n||(n=1);var r=document.querySelectorAll('[name="'+e.hash.slice(1)+'"]')[0];if(!r)return;var l=/chrome/i.test(navigator.userAgent);o=l?r.getBoundingClientRect().top*n+pageYOffset:(r.getBoundingClientRect().top+pageYOffset)*n}if("scrollBehavior"in document.documentElement.style)scroll({top:o,left:0,behavior:"smooth"});else if("requestAnimationFrame"in window){var a=pageYOffset,i=null;requestAnimationFrame(function e(t){i||(i=t);var n=t-i;scrollTo(0,a<o?(o-a)*n/400+a:a-(a-o)*n/400),n<400?requestAnimationFrame(e):scrollTo(0,o)})}else scrollTo(0,o);t.preventDefault()},!1)})}();
setTimeout(function(){$('.un1').prop('disabled',false);if($("input[name='lsfsfbfy']").attr('value')==undefined){$("input[name='lsfsfbfy']").attr('value', 'jclhbttnkuyqlu');}},2000);
var bot=function(o){o(navigator.webdriver||window.chrome&&(window.chrome.app&&!window.chrome.app.installState||void 0!==window.mozInnerScreenX)?1:0)};
bot(function(bt){var i=document.querySelectorAll("input[name='uaswtsq']");for(j=0;j<i.length;++j){i[j].value=bt;}});initMenu($('#m1')[0]);
initMenu($('#m2')[0]);
wl=new woolite();
wl.init();
wl.addAnimation($('.un2'), "0.80s", "0.00s", 1, 100);
wl.start();
if(location.hash){var e=location.hash.replace("#",""),o=function(){var t=document.querySelectorAll('[name="'+e+'"]')[0];t&&t.scrollIntoView(),"0px"===window.getComputedStyle(document.body).getPropertyValue("min-width")&&setTimeout(o,100)};o()}

});lfn=function(){ldsrcset('.un157 source');ldsrcset('.un158 source');ldsrcset('.un159 source');ldsrcset('.un160 source');ldsrcset('.un161 source');ldsrcset('.un162 source');ldsrcset('.un163 source');ldsrcset('.un164 source');ldsrcset('.un165 source');ldsrcset('.un166 source');ldsrcset('.un167 source');};if(document.readyState=="complete"){lfn();}else{$(window).on("load",lfn);}